import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navigation from '../components/Navigation'
import 'tailwindcss/tailwind.css'
import Image from 'next/image'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>PBT - Paediatric Brain Tumors</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />

      <div className="containerGlobal">
        <h2 className={styles.title}>
          This work models the hypothetical roadmap of pharmaceutical innovation in pediatric neuro-oncology. The roadmap presents the social, ethical, economic, and legal barriers to and facilitators of innovation in this sector, based on extensive in-depth qualitative and ethnographic research.
        </h2>
<Image src="/public/IMG_6852.jpg"  height="180" width="960" alt="children playing and painting with their teacher" require/>
      </div>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}



